name: Update GitHub Profile README Hourly

on:
  schedule:
#    - cron: "0 * * * *"  # Run at minute 0 every hour (hourly)
    - cron: "*/5 * * * *"   # Every 5 minutes
  workflow_dispatch:      # Manual trigger support

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date and hour
        run: echo "DATE=$(date +%Y%m%d%H)" >> $GITHUB_ENV

      - name: Update README with new date-hour parameter
        run: |
          sed -i 's|\(https://readme-streak-stats-ten.vercel.app?user=MrDeveloperJIS\)[^)]*|\1\&date='${DATE}'|' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update streak stats with date=${DATE}" || echo "No changes to commit"
          git push
